POS_SP/Models/InstallmentSchedulePayment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace POS_SP.Models
{
    public class InstallmentSchedulePayment
    {
        public int Id { get; set; }

        public bool IsPaid { get; set; }

        [Display(Name = "Schedule Date"), DataType(DataType.Date)]
        public DateTime ScheduleDate { get; set; }

        [Display(Name = "Schedule Amount")]
        public double ScheduleAmount { get; set; }

        [Display(Name = "Payment Date"), DataType(DataType.Date)]
        public DateTime PaymentDate { get; set; }

        [Display(Name = "Paid Amount")]
        public double PaidAmount { get; set; }

        [Display(Name = "Fine Amount")]
        public double FineAmount { get; set; }

        [Display(Name = "Due Amount")]
        public double DueAmount { get; set; }

        [Display(Name = "Total Paid")]
        public double TotalPaid { get; set; }

        [Display(Name = "Total Due")]
        public double TotalDue { get; set; }

        [Display(Name = "Sale Number")]
        public int SalesId { get; set; }

        public Sale Sale { get; set; }
    }
}

POS_SP/Controllers/InstallmentSchedulePaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS_SP.Data;
using POS_SP.Models;

namespace POS_SP.Controllers
{
    public class InstallmentSchedulePaymentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InstallmentSchedulePaymentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: InstallmentSchedulePayments
        public async Task<IActionResult> Index()
        {
            return View(await _context.InstallmentSchedulePayments.ToListAsync());
        }

        // GET: InstallmentSchedulePayments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var installmentSchedulePayment = await _context.InstallmentSchedulePayments
                .SingleOrDefaultAsync(m => m.Id == id);
            if (installmentSchedulePayment == null)
            {
                return NotFound();
            }

            return View(installmentSchedulePayment);
        }

        // GET: InstallmentSchedulePayments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: InstallmentSchedulePayments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ScheduleDate,ScheduleAmount,PaymentDate,PaidAmount,FineAmount,DueAmount,TotalPaid,TotalDue,SalesId")] InstallmentSchedulePayment installmentSchedulePayment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(installmentSchedulePayment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(installmentSchedulePayment);
        }

        // GET: InstallmentSchedulePayments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var installmentSchedulePayment = await _context.InstallmentSchedulePayments.SingleOrDefaultAsync(m => m.Id == id);
            if (installmentSchedulePayment == null)
            {
                return NotFound();
            }
            return View(installmentSchedulePayment);
        }

        // POST: InstallmentSchedulePayments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ScheduleDate,ScheduleAmount,PaymentDate,PaidAmount,FineAmount,DueAmount,TotalPaid,TotalDue,SalesId")] InstallmentSchedulePayment installmentSchedulePayment)
        {
            if (id != installmentSchedulePayment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(installmentSchedulePayment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstallmentSchedulePaymentExists(installmentSchedulePayment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(installmentSchedulePayment);
        }

        // GET: InstallmentSchedulePayments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var installmentSchedulePayment = await _context.InstallmentSchedulePayments
                .SingleOrDefaultAsync(m => m.Id == id);
            if (installmentSchedulePayment == null)
            {
                return NotFound();
            }

            return View(installmentSchedulePayment);
        }

        // POST: InstallmentSchedulePayments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var installmentSchedulePayment = await _context.InstallmentSchedulePayments.SingleOrDefaultAsync(m => m.Id == id);
            _context.InstallmentSchedulePayments.Remove(installmentSchedulePayment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstallmentSchedulePaymentExists(int id)
        {
            return _context.InstallmentSchedulePayments.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult FindSchedule()
        {
            return View();
        }

        public IActionResult UpdateSchedule(int id)
        {
            var result = _context.InstallmentSchedulePayments
                .Where(x => x.SalesId == id)
                .Include(x => x.Sale)
                .ToList();

            if (result == null)
            {
                return RedirectToAction(nameof(FindSchedule));
            }

            return View(result);
        }

        [HttpPost]
        public IActionResult PayInstallment(int id, DateTime paymentDate, double paidAmount, double fineAmount)
        {
            var schedule = _context.InstallmentSchedulePayments.Find(id);
            schedule.PaymentDate = paymentDate;
            schedule.PaidAmount = paidAmount;
            schedule.FineAmount = fineAmount;
            schedule.DueAmount = schedule.DueAmount - paidAmount;
            schedule.TotalPaid = schedule.TotalPaid + paidAmount;
            schedule.TotalDue = schedule.TotalDue - paidAmount;
            schedule.IsPaid = true;
            _context.InstallmentSchedulePayments.Update(schedule);
            _context.SaveChanges();
            return RedirectToAction(nameof(UpdateSchedule), new { id = schedule.SalesId });
        }
    }
}

POS_SP/Views/InstallmentSchedulePayments/Create.cshtml
@model POS_SP.Models.InstallmentSchedulePayment

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>InstallmentSchedulePayment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ScheduleDate" class="control-label"></label>
                <input asp-for="ScheduleDate" class="form-control" />
                <span asp-validation-for="ScheduleDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScheduleAmount" class="control-label"></label>
                <input asp-for="ScheduleAmount" class="form-control" />
                <span asp-validation-for="ScheduleAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input asp-for="PaymentDate" class="form-control" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaidAmount" class="control-label"></label>
                <input asp-for="PaidAmount" class="form-control" />
                <span asp-validation-for="PaidAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FineAmount" class="control-label"></label>
                <input asp-for="FineAmount" class="form-control" />
                <span asp-validation-for="FineAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueAmount" class="control-label"></label>
                <input asp-for="DueAmount" class="form-control" />
                <span asp-validation-for="DueAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPaid" class="control-label"></label>
                <input asp-for="TotalPaid" class="form-control" />
                <span asp-validation-for="TotalPaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalDue" class="control-label"></label>
                <input asp-for="TotalDue" class="form-control" />
                <span asp-validation-for="TotalDue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalesId" class="control-label"></label>
                <input asp-for="SalesId" class="form-control" />
                <span asp-validation-for="SalesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

POS_SP/Views/InstallmentSchedulePayments/Delete.cshtml
@model POS_SP.Models.InstallmentSchedulePayment

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InstallmentSchedulePayment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ScheduleDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ScheduleDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ScheduleAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ScheduleAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaidAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaidAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FineAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FineAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DueAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DueAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalPaid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalPaid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalDue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalDue)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SalesId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SalesId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

POS_SP/Views/InstallmentSchedulePayments/Details.cshtml
@model POS_SP.Models.InstallmentSchedulePayment

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>InstallmentSchedulePayment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ScheduleDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ScheduleDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ScheduleAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ScheduleAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaidAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaidAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FineAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FineAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DueAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DueAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalPaid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalPaid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalDue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalDue)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SalesId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SalesId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

POS_SP/Views/InstallmentSchedulePayments/Edit.cshtml
@model POS_SP.Models.InstallmentSchedulePayment

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>InstallmentSchedulePayment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ScheduleDate" class="control-label"></label>
                <input asp-for="ScheduleDate" class="form-control" />
                <span asp-validation-for="ScheduleDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScheduleAmount" class="control-label"></label>
                <input asp-for="ScheduleAmount" class="form-control" />
                <span asp-validation-for="ScheduleAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input asp-for="PaymentDate" class="form-control" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaidAmount" class="control-label"></label>
                <input asp-for="PaidAmount" class="form-control" />
                <span asp-validation-for="PaidAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FineAmount" class="control-label"></label>
                <input asp-for="FineAmount" class="form-control" />
                <span asp-validation-for="FineAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueAmount" class="control-label"></label>
                <input asp-for="DueAmount" class="form-control" />
                <span asp-validation-for="DueAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPaid" class="control-label"></label>
                <input asp-for="TotalPaid" class="form-control" />
                <span asp-validation-for="TotalPaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalDue" class="control-label"></label>
                <input asp-for="TotalDue" class="form-control" />
                <span asp-validation-for="TotalDue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalesId" class="control-label"></label>
                <input asp-for="SalesId" class="form-control" />
                <span asp-validation-for="SalesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

POS_SP/Views/InstallmentSchedulePayments/FindSchedule.cshtml
@{
    ViewData["Title"] = "FindSchedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="alert alert-info">Installment Schedule</h2>
<div class="row">
    <div class="col-md-12">
        <form class="form-inline" method="post" asp-controller="InstallmentSchedulePayments" asp-action="UpdateSchedule">
            <div class="form-group">
                <label class="control-label">Sales Number: </label>
                <input name="id" type="text" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

POS_SP/Views/InstallmentSchedulePayments/Index.cshtml
@model IEnumerable<POS_SP.Models.InstallmentSchedulePayment>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ScheduleDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ScheduleAmount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PaymentDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PaidAmount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FineAmount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DueAmount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPaid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalDue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SalesId)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ScheduleDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScheduleAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaidAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FineAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPaid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalDue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalesId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

POS_SP/Views/InstallmentSchedulePayments/UpdateSchedule.cshtml
@model IEnumerable<InstallmentSchedulePayment>
@{
    ViewData["Title"] = "UpdateSchedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int serialNo = 0;
    double scheduleAmount = 0;
}

<h2 class="alert alert-info">Installment Schedule</h2>
<div class="row">
    <div class="col-md-12">
        <form class="form-inline" method="post" asp-controller="InstallmentSchedulePayments" asp-action="UpdateSchedule">
            <div class="form-group">
                <label class="control-label">Sales Number: </label>
                <input name="id" type="text" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <hr />
        <div>
            <table class="table table-bordered table-responsive table-hover">
                <thead>
                    <tr>
                        <th>SL No.</th>
                        <th>Schedule Date</th>
                        <th>Amount</th>
                        <th>Payment Date</th>
                        <th>Paid Amount</th>
                        <th>Fine Amount</th>
                        <th>Due Amount</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        ++serialNo;
                        scheduleAmount = item.ScheduleAmount;
                    <tr>
                        <td>@serialNo</td>
                        <td>@item.ScheduleDate.ToString("dd-MM-yyyy")</td>
                        <td>@item.ScheduleAmount</td>
                        @if (item.PaymentDate == DateTime.MinValue)
                        {
                            <td>Not Paid</td>
                        }
                        else
                        {
                            <td>@item.PaymentDate.ToString("dd-MM-yyyy")</td>
                        }
                        <td>@item.PaidAmount</td>
                        <td>@item.FineAmount</td>
                        <td>@item.DueAmount</td>
                        @if (item.IsPaid == true)
                        {
                            <td><button class="btn btn-link" disabled>Paid</button></td>
                        }
                        else
                        {
                            <td><button class="btn btn-link payNow" value="@item.Id">Pay Now</button></td>
                        }

                    </tr>
                    }
                </tbody>
            </table>
        </div>
        <div  class="col-md-6" id="payNowForm" title="Installment Payment Form">
            <form id="payForm" class="form" method="post" asp-controller="InstallmentSchedulePayments" asp-action="PayInstallment">
                <div class="form-group">
                    <label class="control-label">Date </label>
                    <input name="paymentDate" type="date" class="form-control dateTimeNow">
                </div>
                <div class="form-group">
                    <label class="control-label">Amount </label>
                    <input name="paidAmount" type="number" class="form-control" value="@scheduleAmount">
                </div>
                <div class="form-group">
                    <label class="control-label">Fine </label>
                    <input name="fineAmount" type="number" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>
        $("#payNowForm").dialog({
            width: "auto",
            modal: true,
            resizable: false,
            autoOpen: false,
            show: {
                effect: "fade",
                duration: 500
            },
            hide: {
                effect: "fade",
                duration: 500
            }
        });

        $('.payNow').on('click', function () {
            let id = $(this).val();
            console.log(id);
            $('<input>')
                .attr('type', 'hidden')
                .attr('value', id)
                .attr('name', 'id')
                .appendTo('#payForm');
            $("#payNowForm").dialog("open");
        });
    </script>
}