POS_SP/Controllers/PurchasesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS_SP.Data;
using POS_SP.Models;
using POS_SP.Services;

namespace POS_SP.Controllers
{
    public class PurchasesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IStockService _stockService;

        public PurchasesController(ApplicationDbContext context, IStockService stockService)
        {
            _context = context;
            _stockService = stockService;
        }
        
        public async Task<IActionResult> Index(string currentFilter, string searching, int? page)
        {
            if (searching != null)
            {
                page = 1;
            }
            else
            {
                searching = currentFilter;
            }

            ViewData["currentFilter"] = searching;

            var purchase = _context.Purchases
                .Include(s => s.Supplier)
                .Include(x => x.PurchaseDetails)
                .ThenInclude(x => x.Product)
                .OrderByDescending(x => x.PurchaseDate)
                .AsQueryable();

            if (!String.IsNullOrEmpty(searching))
            {
                purchase = purchase.Where(e => e.OrderRefNo.Contains(searching) || e.Supplier.CompanyName.Contains(searching));
            }

            int pageSize = 10;

            return View(await PaginatedList<Purchase>.CreateAsync(purchase.AsNoTracking(), page ?? 1, pageSize));
        }
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchase = await _context.Purchases
                .Include(p => p.Supplier)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase);
        }
        
        public IActionResult Create()
        {
            ViewData["SupplierId"] = new SelectList(_context.Set<Supplier>(), "Id", "CompanyName");
            ViewData["CategoryId"] = new SelectList(_context.Set<Category>(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Purchase model)
        {
            var resultExist = _context.Purchases.Where(x => x.OrderRefNo == model.OrderRefNo).FirstOrDefault();

            if (resultExist == null)
            {
                Purchase purchase = new Purchase
                {
                    OrderNo = "P-" + DateTime.UtcNow.Millisecond,
                    OrderRefNo = model.OrderRefNo,
                    PurchaseDate = model.PurchaseDate,
                    SupplierId = model.SupplierId,
                    TaxPercent = model.TaxPercent,
                    TaxAmount = model.TaxAmount,
                    VatPercent = model.VatPercent,
                    VatAmount = model.VatAmount,
                    DiscountPercent = model.DiscountPercent,
                    DiscountAmount = model.DiscountAmount,
                    PaymentType = model.PaymentType,
                    PaymentAmount = model.PaymentAmount,
                    DueAmount = model.DueAmount,
                    TotalAmount = model.TotalAmount
                };
                _context.Purchases.Add(purchase);
                _context.SaveChanges();
                foreach (var item in model.PurchaseDetails)
                {
                    PurchaseDetail purchaseDetail = new PurchaseDetail
                    {
                        PurchaseId = purchase.Id,
                        ProductId = item.ProductId,
                        UnitPrice = item.UnitPrice,
                        UOM = item.UOM,
                        Quantity = item.Quantity,
                        IndividualTotal = item.IndividualTotal
                    };
                    _context.PurchaseDetails.Add(purchaseDetail);
                    _context.SaveChanges();

                    _stockService.StockMaintain(DateTime.Now.Date, item);
                    _stockService.AddStockDetail("Purchase", item);
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchase = await _context.Purchases.SingleOrDefaultAsync(m => m.Id == id);
            if (purchase == null)
            {
                return NotFound();
            }
            ViewData["SupplierId"] = new SelectList(_context.Set<Supplier>(), "Id", "Address1", purchase.SupplierId);
            return View(purchase);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PurchaseDate,OrderRefNo,SupplierId,OrderNo,LoadingBill,LabourCost,TaxPercent,TaxAmount,VatPercent,VatAmount,DiscountPercent,DiscountAmount,PaymentType,PaymentAmount,DueAmount,TotalAmount")] Purchase purchase)
        {
            if (id != purchase.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PurchaseExists(purchase.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SupplierId"] = new SelectList(_context.Set<Supplier>(), "Id", "Address1", purchase.SupplierId);
            return View(purchase);
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchase = await _context.Purchases
                .Include(p => p.Supplier)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var purchase = await _context.Purchases.SingleOrDefaultAsync(m => m.Id == id);
            _context.Purchases.Remove(purchase);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PurchaseExists(int id)
        {
            return _context.Purchases.Any(e => e.Id == id);
        }
    }
}

POS_SP/Views/Purchases/Create.cshtml
@model PurchaseViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="alert alert-info">Create Purchase</h2>
<div class="row">
    <div class="col-md-12">
        <form id="purchaseForm" class="form-horizontal" action="Create" method="post">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Purchase.OrderRefNo" class="control-label col-sm-4"></label>
                        <div class="col-sm-7">
                            <input id="orderRefNumber" name="OrderRefNo" type="number" asp-for="Purchase.OrderRefNo" class="form-control" title="Enter Order Reference Number." />
                            <span asp-validation-for="Purchase.OrderRefNo" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Purchase.SupplierId" class="control-label col-sm-4"></label>
                        <div class="col-sm-7">
                            <select id="supplierId" asp-for="Purchase.SupplierId" class="form-control" asp-items="ViewBag.SupplierId">
                                <option value="0">Select Client from list...</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Purchase.PurchaseDate" class="control-label col-sm-4"></label>
                        <div class="col-sm-7">
                            <input id="purchasesDate" type="date" asp-for="Purchase.PurchaseDate" class="form-control dateTimeNow" />
                            <span asp-validation-for="Purchase.PurchaseDate" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <table id="table" class="table table-hover table-responsive ">
                <thead>
                    <tr>
                        <th>Category</th>
                        <th>Sub Category</th>
                        <th>Brand</th>
                        <th>Product</th>
                        <th>Unit Price</th>
                        <th>Unit</th>
                        <th>Quantity</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="col-md-2">
                            <select id="categoryId" class="form-control" asp-items="ViewBag.CategoryId">
                                <option value="0">Select Category From List...</option>
                            </select>
                        </td>
                        <td>
                            <select id="subCategoryId" class="form-control">
                                <option value="0">Select Sub Category...</option>
                            </select>
                        </td>
                        <td>
                            <select id="brandId" class="form-control">
                                <option value="0">Select Brand...</option>
                            </select>
                        </td>
                        <td class="col-md-2">
                            <select id="productId" asp-for="PurchaseDetail.ProductId" class="form-control"></select>
                        </td>
                        <td class="col-md-1">
                            <input id="unitPrice" asp-for="PurchaseDetail.UnitPrice" class="form-control" />
                        </td>
                        <td class="col-md-1">
                            <input id="uom" asp-for="PurchaseDetail.UOM" class="form-control" />
                        </td>
                        <td class="col-md-1">
                            <input id="quantity" asp-for="PurchaseDetail.Quantity" class="form-control" />
                        </td>
                        <td>
                            <button id="addProduct" class="btn btn-default"><i class="glyphicon glyphicon-plus"></i></button>
                        </td>
                    </tr>
                </tbody>
            </table>
            <hr />
            <table id="productTable" class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Sub Category</th>
                        <th>Brand</th>
                        <th>Product</th>
                        <th>Unit Price</th>
                        <th>Unit</th>
                        <th>Quantity</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody id="tableBody"></tbody>
            </table>
            <hr />
            <div class="col-md-4 col-md-offset-8">
                <p class="col-sm-9"><b>Sub total amount</b></p>
                <p id="subTotalAmount" class="col-sm-3">0.00</p>
            </div>
            <div class="col-md-12"><hr /></div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.LabourCost" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="labourCost" asp-for="Purchase.LabourCost" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">BDT</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.LoadingBill" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="loadingBill" asp-for="Purchase.LoadingBill" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">BDT</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.TaxPercent" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="taxPercent" asp-for="Purchase.TaxPercent" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.TaxAmount" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="taxTaka" asp-for="Purchase.TaxAmount" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">BDT</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.VatPercent" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="vatPercent" asp-for="Purchase.VatPercent" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.VatAmount" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="vatTaka" asp-for="Purchase.VatAmount" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">BDT</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.DiscountPercent" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="discountPercent" asp-for="Purchase.DiscountPercent" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.DiscountAmount" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="discountTaka" asp-for="Purchase.DiscountAmount" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">BDT</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12"><hr /></div>
            <div class="col-md-4 col-md-offset-8">
                <p class="col-sm-9"><b>Total amount</b></p>
                <p id="totalAmount" class="col-sm-3">0.00</p>
            </div>
            <div class="col-md-12"><hr /></div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.PaymentType" class="control-label col-sm-4"></label>
                    <div class="col-sm-7">
                        <select class="form-control" id="paymentType" asp-for="Purchase.PaymentType" asp-items="Html.GetEnumSelectList<PaymentTypes>()"></select>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Purchase.PaymentAmount" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="paymentAmount" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">BDT</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-md-offset-6">
                <div class="form-group">
                    <label asp-for="Purchase.DueAmount" class="control-label col-sm-4"></label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input id="dueAmount" type="number" class="form-control" aria-label="Amount (rounded to the nearest dollar)">
                            <span class="input-group-addon">BDT</span>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-12"><hr /></div>
            <div class="col-md-12"><button id="submitFrom" type="submit" class="btn btn-primary pull-right">Confirm Order</button></div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Purchase.js"></script>
}

POS_SP/Views/Purchases/Delete.cshtml
@model POS_SP.Models.Purchase

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderRefNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderRefNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LoadingBill)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LoadingBill)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LabourCost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LabourCost)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaxPercent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaxPercent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaxAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaxAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VatPercent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VatPercent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VatAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VatAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DiscountPercent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DiscountPercent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DiscountAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DiscountAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DueAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DueAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Supplier.Address1)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

POS_SP/Views/Purchases/Index.cshtml
@model PaginatedList<Purchase>
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
    int serialNo = 0;
}
<h2 class="alert alert-info">Purchase Record</h2>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Index" method="get">
            <div class="form-actions no-color top-buffer">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <input type="text" placeholder="Search.." name="searching" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <input type="submit" value="Search" class="btn btn-primary" />
                        </div>
                    </div>

                    <div class="col-md-2 pull-right">
                        <a href="/Purchases/Create" class="btn btn-primary">Create New</a>
                    </div>

                    <div class="col-md-2 pull-right">
                        <div class="form-group">
                            <a asp-controller="Purchases" asp-action="Index" class="btn btn-primary">Back to Full List</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        @if (Model.Count() == 0)
        {
            <h4>No Record Found</h4>
        }
        else
        {
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Sl No.</th>
                        <th>Order No.</th>
                        <th>Purchase Date</th>
                        <th>Order Refer No.</th>
                        <th>Supplier</th>
                        <th>Tax</th>
                        <th>Vat</th>
                        <th>Discount</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        serialNo++;
                        <tr>
                            <td>@serialNo</td>
                            <td>@item.OrderNo</td>
                            <td>@item.PurchaseDate.ToString("dd/MM/yyyy")</td>
                            <td>@item.OrderRefNo</td>
                            <td>@item.Supplier.CompanyName</td>
                            <td>@item.TaxAmount</td>
                            <td>@item.VatAmount</td>
                            <td>@item.DiscountAmount</td>
                            <td>@item.TotalAmount</td>
                            <td>
                                <button data-toggle="collapse" data-target="#@serialNo" class="btn btn-default"><i class="glyphicon glyphicon-chevron-down"></i></button>
                                <a href="/Purchases/Edit/@item.Id" class="btn btn-default"><i class="glyphicon glyphicon-edit"></i></a>
                                <a href="/Purchases/Delete/@item.Id" class="btn btn-default"><i class="glyphicon glyphicon-trash"></i></a>
                            </td>
                        </tr>
                        <tr id="@serialNo" class="collapse">
                            <td colspan="10">
                                <table class="table table-bordered" style="background-color:#f7f7f7">
                                    <thead>
                                        <tr>
                                            <td>Product</td>
                                            <td>Quantity</td>
                                            <td>Unit</td>
                                            <td>Unit Price</td>
                                            <td>Sub Total</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var detail in item.PurchaseDetails)
                                        {
                                            <tr>
                                                <td>@detail.Product.Name</td>
                                                <td>@detail.Quantity</td>
                                                <td>@detail.UOM</td>
                                                <td>@detail.UnitPrice</td>
                                                <td>@detail.IndividualTotal</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }

        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <ul class="pagination">
            <li>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-page="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @prevDisabled">
                    Previous
                </a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (Model.PageIndex == i)
                {
                    <li class="active">
                        <a asp-action="Index"
                           asp-route-sortOrder="@ViewData["CurrentSort"]"
                           asp-route-page="@i"
                           asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           class="btn btn-default">
                            @i
                        </a>
                    </li>
                }
                else
                {
                    <li>
                        <a asp-action="Index"
                           asp-route-sortOrder="@ViewData["CurrentSort"]"
                           asp-route-page="@i"
                           asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           class="btn btn-default">
                            @i
                        </a>
                    </li>
                }

            }
            <li>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-page="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @nextDisabled">
                    Next
                </a>
            </li>
        </ul>
    </div>
</div>